# Generated by Django 4.2.7 on 2023-11-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='keterangan',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
