# Generated by Django 4.2.6 on 2023-11-23 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_produk_beranda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='beranda',
        ),
    ]
